#!/usr/bin/env python3
"""Regenerate data.yml from structure.yml + tools/*.yml.

Run after editing anything under tools/ or structure.yml:
    python3 scripts/build_data.py
"""
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

HEADER = """\
# DDI Tools Landscape 2 — proposed taxonomy
#
# This file is GENERATED by scripts/build_data.py — do not edit directly.
# Edit structure.yml (category/subcategory order) and tools/*.yml (one file
# per tool) instead, then re-run the script.
#
# Primary categories describe what a tool does.
# second_path entries classify the same item by DDI standard/version without duplication.
# DDI-CDI, SDTL and XKOS are intentionally empty until supporting tools are added.
# The current queXML -> DDI Codebook 2.1 relationship is retained but marked for verification.
# DDI versions are no longer stored in summary_release_rate.
"""


def main() -> None:
    structure = yaml.safe_load((ROOT / "structure.yml").read_text())

    tool_files = sorted((ROOT / "tools").glob("*.yml"))
    tools = [yaml.safe_load(p.read_text()) for p in tool_files]

    for tool, path in zip(tools, tool_files):
        for required in ("category", "subcategory", "name"):
            if required not in tool:
                sys.exit(f"{path}: missing required field '{required}'")

    categories = []
    for category in structure["categories"]:
        cat_out = {"name": category["name"], "subcategories": []}
        for subcategory in category["subcategories"]:
            items = [
                t
                for t in tools
                if t["category"] == category["name"]
                and t["subcategory"] == subcategory["name"]
            ]
            items.sort(key=lambda t: (t.get("order", 0), t["name"]))

            clean_items = []
            for item in items:
                clean = {
                    k: v
                    for k, v in item.items()
                    if k not in ("category", "subcategory", "order")
                }
                clean_items.append(clean)

            cat_out["subcategories"].append(
                {"name": subcategory["name"], "items": clean_items}
            )
        categories.append(cat_out)

    seen = {(t["category"], t["subcategory"]) for t in tools}
    known = {
        (c["name"], s["name"])
        for c in structure["categories"]
        for s in c["subcategories"]
    }
    unknown = seen - known
    if unknown:
        sys.exit(f"tools/*.yml reference unknown category/subcategory pairs: {unknown}")

    with (ROOT / "data.yml").open("w") as f:
        f.write(HEADER + "\n")
        yaml.dump(
            {"categories": categories},
            f,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=True,
            width=88,
        )

    print(f"Wrote data.yml from {len(tool_files)} tool files", file=sys.stderr)


if __name__ == "__main__":
    main()
