#!/usr/bin/env python3
"""Regenerate data.yml and guide.yml from structure.yml + the item files in
ITEM_DIRS.

Run after editing anything under tools/, members/, examples/, profiles/
or structure.yml:
    python3 scripts/build_data.py
"""
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

# Directories holding one .yml file per landscape item.
ITEM_DIRS = ("tools", "members", "examples", "profiles")

HEADER = """\
# DDI Tools Landscape 2 — proposed taxonomy
#
# This file is GENERATED by scripts/build_data.py — do not edit directly.
# Edit structure.yml (category/subcategory order) and the item files in
# tools/, members/, examples/ and profiles/ (one file per item) instead,
# then re-run the script.
#
# Primary categories describe what a tool does.
# second_path entries classify the same item by DDI standard/version without duplication.
# DDI-CDI, SDTL and XKOS are intentionally empty until supporting tools are added.
# The current queXML -> DDI Codebook 2.1 relationship is retained but marked for verification.
# DDI versions are no longer stored in summary_release_rate.
"""

GUIDE_HEADER = """\
# Landscape2 guide
#
# This file is GENERATED by scripts/build_data.py — do not edit directly.
# Category/subcategory introductions come from the optional `guide` field in
# structure.yml; each item's entry comes from its name, homepage_url and
# description in tools/, members/, examples/ or profiles/.
#
# Reference documentation: https://github.com/cncf/landscape2/blob/main/docs/config/guide.yml
"""


class _LiteralStr(str):
    """String dumped in YAML block literal style (|)."""


yaml.add_representer(
    _LiteralStr,
    lambda dumper, data: dumper.represent_scalar(
        "tag:yaml.org,2002:str", data, style="|"
    ),
)


def _one_line(text) -> str:
    return " ".join(str(text or "").split())


def _block(*paragraphs) -> _LiteralStr:
    return _LiteralStr("\n\n".join(p for p in paragraphs if p) + "\n")


def _guide_item(item: dict) -> str:
    name = item["name"]
    if item.get("homepage_url"):
        name = f"[{name}]({item['homepage_url']})"
    description = _one_line(item.get("description"))
    return f"- **{name}**" + (f": {description}" if description else "")


def build_guide(structure: dict, categories: list) -> dict:
    """Guide sections mirror data.yml; empty sections are left out."""
    guide_categories = []
    for category, cat_data in zip(structure["categories"], categories):
        subcategories = []
        for subcategory, sub_data in zip(
            category["subcategories"], cat_data["subcategories"]
        ):
            intro = _one_line(subcategory.get("guide"))
            items = "\n".join(_guide_item(i) for i in sub_data["items"])
            if intro or items:
                subcategories.append(
                    {
                        "subcategory": subcategory["name"],
                        "content": _block(intro, items),
                    }
                )

        intro = _one_line(category.get("guide"))
        if not intro and not subcategories:
            continue
        entry = {"category": category["name"]}
        if intro:
            entry["content"] = _block(intro)
        if subcategories:
            entry["subcategories"] = subcategories
        guide_categories.append(entry)
    return {"categories": guide_categories}


def main() -> None:
    structure = yaml.safe_load((ROOT / "structure.yml").read_text())

    tool_files = sorted(p for d in ITEM_DIRS for p in (ROOT / d).glob("*.yml"))
    tools = [yaml.safe_load(p.read_text()) for p in tool_files]

    for tool, path in zip(tools, tool_files):
        for required in ("category", "subcategory", "name"):
            if required not in tool:
                sys.exit(f"{path}: missing required field '{required}'")

    categories = []
    for category in structure["categories"]:
        cat_out = {"name": category["name"], "subcategories": []}
        for subcategory in category["subcategories"]:
            items = [
                t
                for t in tools
                if t["category"] == category["name"]
                and t["subcategory"] == subcategory["name"]
            ]
            items.sort(key=lambda t: (t.get("order", 0), t["name"]))

            clean_items = []
            for item in items:
                clean = {
                    k: v
                    for k, v in item.items()
                    if k not in ("category", "subcategory", "order")
                }
                clean_items.append(clean)

            cat_out["subcategories"].append(
                {"name": subcategory["name"], "items": clean_items}
            )
        categories.append(cat_out)

    seen = {(t["category"], t["subcategory"]) for t in tools}
    known = {
        (c["name"], s["name"])
        for c in structure["categories"]
        for s in c["subcategories"]
    }
    unknown = seen - known
    if unknown:
        sys.exit(f"Item files reference unknown category/subcategory pairs: {unknown}")

    with (ROOT / "data.yml").open("w") as f:
        f.write(HEADER + "\n")
        yaml.dump(
            {"categories": categories},
            f,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=True,
            width=88,
        )

    with (ROOT / "guide.yml").open("w") as f:
        f.write(GUIDE_HEADER + "\n")
        yaml.dump(
            build_guide(structure, categories),
            f,
            sort_keys=False,
            default_flow_style=False,
            allow_unicode=True,
            width=1000,
        )

    print(
        f"Wrote data.yml and guide.yml from {len(tool_files)} item files",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
